// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Page,
    PageFromJSON,
    PageToJSON,
} from './index';

/**
 * Describes an abstract form
 * @export
 * @interface AbstractForm
 */
export interface AbstractForm  {
    /**
     * 
     * @type {string}
     * @memberof AbstractForm
     */
    id?: string;
    /**
     * 
     * @type {Array<Page>}
     * @memberof AbstractForm
     */
    pages: Array<Page>;
}

export function AbstractFormFromJSON(json: any): AbstractForm {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'pages': (json['pages'] as Array<any>).map(PageFromJSON),
    };
}

export function AbstractFormToJSON(value?: AbstractForm): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'pages': (value.pages as Array<any>).map(PageToJSON),
    };
}


