// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Answer
 */
export interface Answer  {
    /**
     * 
     * @type {string}
     * @memberof Answer
     */
    questionaireId: string;
    /**
     * 
     * @type {string}
     * @memberof Answer
     */
    questionId: string;
    /**
     * 
     * @type {boolean}
     * @memberof Answer
     */
    notApplicable: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof Answer
     */
    values: Array<string>;
}

export function AnswerFromJSON(json: any): Answer {
    return {
        'questionaireId': json['questionaireId'],
        'questionId': json['questionId'],
        'notApplicable': json['notApplicable'],
        'values': json['values'],
    };
}

export function AnswerToJSON(value?: Answer): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'questionaireId': value.questionaireId,
        'questionId': value.questionId,
        'notApplicable': value.notApplicable,
        'values': value.values,
    };
}


