// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ResultSection,
    ResultSectionFromJSON,
    ResultSectionToJSON,
    TutorReport,
    TutorReportFromJSON,
    TutorReportToJSON,
} from './index';

/**
 * 
 * @export
 * @interface CourseReport
 */
export interface CourseReport  {
    /**
     * 
     * @type {string}
     * @memberof CourseReport
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseReport
     */
    courseId?: string;
    /**
     * 
     * @type {Date}
     * @memberof CourseReport
     */
    generated?: Date;
    /**
     * 
     * @type {Array<TutorReport>}
     * @memberof CourseReport
     */
    tutorReports?: Array<TutorReport>;
    /**
     * contains results only concerning course
     * @type {Array<ResultSection>}
     * @memberof CourseReport
     */
    sections?: Array<ResultSection>;
}

export function CourseReportFromJSON(json: any): CourseReport {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'generated': !exists(json, 'generated') ? undefined : new Date(json['generated']),
        'tutorReports': !exists(json, 'tutorReports') ? undefined : (json['tutorReports'] as Array<any>).map(TutorReportFromJSON),
        'sections': !exists(json, 'sections') ? undefined : (json['sections'] as Array<any>).map(ResultSectionFromJSON),
    };
}

export function CourseReportToJSON(value?: CourseReport): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'courseId': value.courseId,
        'generated': value.generated === undefined ? undefined : value.generated.toISOString(),
        'tutorReports': value.tutorReports === undefined ? undefined : (value.tutorReports as Array<any>).map(TutorReportToJSON),
        'sections': value.sections === undefined ? undefined : (value.sections as Array<any>).map(ResultSectionToJSON),
    };
}


