// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * creates a link between courses and prof
 * @export
 * @interface CourseProf
 */
export interface CourseProf  {
    /**
     * 
     * @type {string}
     * @memberof CourseProf
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseProf
     */
    courseId: string;
    /**
     * 
     * @type {string}
     * @memberof CourseProf
     */
    profId: string;
}

export function CourseProfFromJSON(json: any): CourseProf {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'courseId': json['courseId'],
        'profId': json['profId'],
    };
}

export function CourseProfToJSON(value?: CourseProf): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'courseId': value.courseId,
        'profId': value.profId,
    };
}


