// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CourseReport,
    CourseReportFromJSON,
    CourseReportToJSON,
    ResultSection,
    ResultSectionFromJSON,
    ResultSectionToJSON,
} from './index';

/**
 * 
 * @export
 * @interface CourseProfReport
 */
export interface CourseProfReport  {
    /**
     * 
     * @type {string}
     * @memberof CourseProfReport
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseProfReport
     */
    courseProfId?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseProfReport
     */
    courseId?: string;
    /**
     * 
     * @type {Date}
     * @memberof CourseProfReport
     */
    generated?: Date;
    /**
     * 
     * @type {CourseReport}
     * @memberof CourseProfReport
     */
    courseReport?: CourseReport;
    /**
     * contains results only concerning courseProf
     * @type {Array<ResultSection>}
     * @memberof CourseProfReport
     */
    sections?: Array<ResultSection>;
}

export function CourseProfReportFromJSON(json: any): CourseProfReport {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'courseProfId': !exists(json, 'courseProfId') ? undefined : json['courseProfId'],
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'generated': !exists(json, 'generated') ? undefined : new Date(json['generated']),
        'courseReport': !exists(json, 'courseReport') ? undefined : CourseReportFromJSON(json['courseReport']),
        'sections': !exists(json, 'sections') ? undefined : (json['sections'] as Array<any>).map(ResultSectionFromJSON),
    };
}

export function CourseProfReportToJSON(value?: CourseProfReport): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'courseProfId': value.courseProfId,
        'courseId': value.courseId,
        'generated': value.generated === undefined ? undefined : value.generated.toISOString(),
        'courseReport': CourseReportToJSON(value.courseReport),
        'sections': value.sections === undefined ? undefined : (value.sections as Array<any>).map(ResultSectionToJSON),
    };
}


