// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AbstractForm,
    AbstractFormFromJSON,
    AbstractFormToJSON,
} from './index';

/**
 * 
 * @export
 * @interface Form
 */
export interface Form  {
    /**
     * 
     * @type {string}
     * @memberof Form
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Form
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Form
     */
    termId: string;
    /**
     * 
     * @type {AbstractForm}
     * @memberof Form
     */
    abstractForm: AbstractForm;
}

export function FormFromJSON(json: any): Form {
    return {
        'id': json['id'],
        'name': json['name'],
        'termId': json['termId'],
        'abstractForm': AbstractFormFromJSON(json['abstractForm']),
    };
}

export function FormToJSON(value?: Form): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'termId': value.termId,
        'abstractForm': AbstractFormToJSON(value.abstractForm),
    };
}


