// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Onetime invitation to take a certain evaluation of a course.
 * @export
 * @interface Invitation
 */
export interface Invitation  {
    /**
     * 
     * @type {string}
     * @memberof Invitation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Invitation
     */
    courseId: string;
    /**
     * 
     * @type {boolean}
     * @memberof Invitation
     */
    used?: boolean;
}

export function InvitationFromJSON(json: any): Invitation {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'courseId': json['courseId'],
        'used': !exists(json, 'used') ? undefined : json['used'],
    };
}

export function InvitationToJSON(value?: Invitation): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'courseId': value.courseId,
        'used': value.used,
    };
}


