// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * used to keep track of courses over many years.
 * @export
 * @interface Module
 */
export interface Module  {
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Module
     */
    description: string;
    /**
     * Determines which faculty is in charge.
     * @type {string}
     * @memberof Module
     */
    facultyId: string;
}

export function ModuleFromJSON(json: any): Module {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'],
        'facultyId': json['facultyId'],
    };
}

export function ModuleToJSON(value?: Module): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'facultyId': value.facultyId,
    };
}


