// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Possibly labeled selection option
 * @export
 * @interface Option
 */
export interface Option  {
    /**
     * 
     * @type {string}
     * @memberof Option
     */
    id?: string;
    /**
     * Map of translations for a given string. A string might contain markdown code.
     * @type {{ [key: string]: string; }}
     * @memberof Option
     */
    label: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof Option
     */
    value: number;
    /**
     * Used to determine position in array
     * @type {number}
     * @memberof Option
     */
    position?: number;
}

export function OptionFromJSON(json: any): Option {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'label': json['label'],
        'value': json['value'],
        'position': !exists(json, 'position') ? undefined : json['position'],
    };
}

export function OptionToJSON(value?: Option): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'label': value.label,
        'value': value.value,
        'position': value.position,
    };
}


