// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Section,
    SectionFromJSON,
    SectionToJSON,
} from './index';

/**
 * Group of sections that belong together
 * @export
 * @interface Page
 */
export interface Page  {
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    id?: string;
    /**
     * 
     * @type {Array<Section>}
     * @memberof Page
     */
    sections: Array<Section>;
    /**
     * Used to determine position in array
     * @type {number}
     * @memberof Page
     */
    position?: number;
}

export function PageFromJSON(json: any): Page {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'sections': (json['sections'] as Array<any>).map(SectionFromJSON),
        'position': !exists(json, 'position') ? undefined : json['position'],
    };
}

export function PageToJSON(value?: Page): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'sections': (value.sections as Array<any>).map(SectionToJSON),
        'position': value.position,
    };
}


