// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Answer,
    AnswerFromJSON,
    AnswerToJSON,
} from './index';

/**
 * A fully completed form.
 * @export
 * @interface Questionaire
 */
export interface Questionaire  {
    /**
     * 
     * @type {string}
     * @memberof Questionaire
     */
    id?: string;
    /**
     * 
     * @type {Array<Answer>}
     * @memberof Questionaire
     */
    answers: Array<Answer>;
}

export function QuestionaireFromJSON(json: any): Questionaire {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'answers': (json['answers'] as Array<any>).map(AnswerFromJSON),
    };
}

export function QuestionaireToJSON(value?: Questionaire): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'answers': (value.answers as Array<any>).map(AnswerToJSON),
    };
}


