// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultPair
 */
export interface ResultPair  {
    /**
     * Map of translations for a given string. A string might contain markdown code.
     * @type {{ [key: string]: string; }}
     * @memberof ResultPair
     */
    label?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof ResultPair
     */
    position?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultPair
     */
    value?: string;
}

export function ResultPairFromJSON(json: any): ResultPair {
    return {
        'label': !exists(json, 'label') ? undefined : json['label'],
        'position': !exists(json, 'position') ? undefined : json['position'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ResultPairToJSON(value?: ResultPair): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'label': value.label,
        'position': value.position,
        'value': value.value,
    };
}


