// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Term
 */
export interface Term  {
    /**
     * 
     * @type {string}
     * @memberof Term
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Term
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Term
     */
    begin: Date;
    /**
     * 
     * @type {Date}
     * @memberof Term
     */
    end: Date;
}

export function TermFromJSON(json: any): Term {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'begin': new Date(json['begin']),
        'end': new Date(json['end']),
    };
}

export function TermToJSON(value?: Term): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'begin': value.begin.toISOString().substr(0,10),
        'end': value.end.toISOString().substr(0,10),
    };
}


