// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CourseProfReport,
    CourseProfReportFromJSON,
    CourseProfReportToJSON,
} from './index';

/**
 * 
 * @export
 * @interface TermReport
 */
export interface TermReport  {
    /**
     * 
     * @type {string}
     * @memberof TermReport
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof TermReport
     */
    generated?: Date;
    /**
     * 
     * @type {string}
     * @memberof TermReport
     */
    termId?: string;
    /**
     * 
     * @type {string}
     * @memberof TermReport
     */
    facultyId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TermReport
     */
    censored?: boolean;
    /**
     * 
     * @type {Array<CourseProfReport>}
     * @memberof TermReport
     */
    courseProfReports?: Array<CourseProfReport>;
}

export function TermReportFromJSON(json: any): TermReport {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'generated': !exists(json, 'generated') ? undefined : new Date(json['generated']),
        'termId': !exists(json, 'termId') ? undefined : json['termId'],
        'facultyId': !exists(json, 'facultyId') ? undefined : json['facultyId'],
        'censored': !exists(json, 'censored') ? undefined : json['censored'],
        'courseProfReports': !exists(json, 'courseProfReports') ? undefined : (json['courseProfReports'] as Array<any>).map(CourseProfReportFromJSON),
    };
}

export function TermReportToJSON(value?: TermReport): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'generated': value.generated === undefined ? undefined : value.generated.toISOString(),
        'termId': value.termId,
        'facultyId': value.facultyId,
        'censored': value.censored,
        'courseProfReports': value.courseProfReports === undefined ? undefined : (value.courseProfReports as Array<any>).map(CourseProfReportToJSON),
    };
}


