// tslint:disable
/**
 * Evaluation
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ResultSection,
    ResultSectionFromJSON,
    ResultSectionToJSON,
} from './index';

/**
 * 
 * @export
 * @interface TutorReport
 */
export interface TutorReport  {
    /**
     * 
     * @type {string}
     * @memberof TutorReport
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TutorReport
     */
    tutorId?: string;
    /**
     * 
     * @type {string}
     * @memberof TutorReport
     */
    courseId?: string;
    /**
     * 
     * @type {Date}
     * @memberof TutorReport
     */
    generated?: Date;
    /**
     * 
     * @type {Array<ResultSection>}
     * @memberof TutorReport
     */
    sections?: Array<ResultSection>;
}

export function TutorReportFromJSON(json: any): TutorReport {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'tutorId': !exists(json, 'tutorId') ? undefined : json['tutorId'],
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
        'generated': !exists(json, 'generated') ? undefined : new Date(json['generated']),
        'sections': !exists(json, 'sections') ? undefined : (json['sections'] as Array<any>).map(ResultSectionFromJSON),
    };
}

export function TutorReportToJSON(value?: TutorReport): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'tutorId': value.tutorId,
        'courseId': value.courseId,
        'generated': value.generated === undefined ? undefined : value.generated.toISOString(),
        'sections': value.sections === undefined ? undefined : (value.sections as Array<any>).map(ResultSectionToJSON),
    };
}


