version: "3"
networks:
  app-tier:
    driver: bridge
services:
  db:
    image: bitnami/postgresql:latest
    restart: always
    env_file: db.env
    volumes:
      - db-data:/bitnami/postgresql
    networks:
      - app-tier
  ostseee:
    build: server
    image: ostseee:latest
    restart: always
    container_name: ostseee
    env_file: ./ostsee.env
    networks:
      - app-tier
    depends_on:
      - db
  web:
    build: .
    image: ostseee_proxy:latest
    container_name: ostseee_proxy
    restart: always
    ports:
      - "127.0.0.1:3081:8081"
      - "127.0.0.1:3082:8082"
    depends_on:
      - ostseee
    networks:
      - app-tier

volumes:
  db-data:
