/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import uuid "github.com/satori/go.uuid"

// Questionaire - A fully completed form.
type Questionaire struct {
	Base
	CourseId uuid.UUID
	Answers  []Answer `json:"answers"`
}
