/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Course struct {

	Id string `json:"id,omitempty"`

	ModuleId string `json:"moduleId"`

	FormId string `json:"formId"`

	TermId string `json:"termId"`

	Location string `json:"location"`

	NumberOfStudents int32 `json:"numberOfStudents"`

	Language string `json:"language"`

	// Third-party Key, that identifies a course
	ThirdPartyKey string `json:"thirdPartyKey,omitempty"`

	// current status for sent mails for this course
	Progress string `json:"progress"`

	// Describes whether, this course is published to profs and tutors.
	Clearance string `json:"clearance"`

	Tutors []Tutor `json:"tutors"`
}
