/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import uuid "github.com/satori/go.uuid"

// CourseProf - creates a link between courses and prof
type CourseProf struct {
	Base

	CourseId uuid.UUID `gorm:"type:uuid;" json:"courseId"`

	ProfId uuid.UUID `gorm:"type:uuid;" json:"profId"`
}
