/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Module - used to keep track of courses over many years.
type Module struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name"`

	Description string `json:"description"`

	// Determines which faculty is in charge.
	FacultyId string `json:"facultyId"`
}
