/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"

	uuid "github.com/satori/go.uuid"
)

type TermReport struct {
	Base

	Generated time.Time `json:"generated,omitempty"`

	TermId uuid.UUID `gorm:"type:uuid;" json:"termId,omitempty"`

	FacultyId uuid.UUID `gorm:"type:uuid;" json:"facultyId,omitempty"`

	Censored bool `json:"censored,omitempty"`

	CourseProfReports []CourseProfReport `json:"courseProfReports,omitempty"`
}
