/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import uuid "github.com/satori/go.uuid"

// Invitation - Onetime invitation to take a certain evaluation of a course.
type Invitation struct {
	Base

	CourseId uuid.UUID `gorm:"type:uuid;" json:"courseId"`

	ValidBegin string `json:"validBegin"`
	ValidEnd   string `json:"validEnd"`
	Used       bool   `json:"used,omitempty"`
}
