/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Invitation - Onetime invitation to take a certain evaluation of a course.
type Invitation struct {

	Id string `json:"id,omitempty"`

	CourseId string `json:"courseId"`

	Used bool `json:"used,omitempty"`
}
