/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"

	uuid "github.com/satori/go.uuid"
)

type CourseReport struct {
	Base

	CourseId uuid.UUID `gorm:"type:uuid;" json:"courseId,omitempty"`

	Generated time.Time `json:"generated,omitempty"`

	TutorReports []TutorReport `json:"tutorReports,omitempty"`

	// contains results only concerning course
	Sections []ResultSection `json:"sections,omitempty"`
}
