/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import uuid "github.com/satori/go.uuid"

// Option - Possibly labeled selection option
type Option struct {
	Base
	LabeledObject
	Value      int32     `json:"value"`
	QuestionId uuid.UUID `gorm:"type:uuid" json:"-"`
}
