/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import uuid "github.com/satori/go.uuid"

type Form struct {
	Base

	Name string `json:"name"`

	TermId uuid.UUID `gorm:"type:uuid;" json:"termId"`

	AbstractForm AbstractForm `json:"abstractForm" gorm:"foreignkey:FormId"`
}
