/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import uuid "github.com/satori/go.uuid"

// Page - Group of sections that belong together
type Page struct {
	Base
	Position       int32     `json:"position"`
	AbstractFormId uuid.UUID `gorm:"type:uuid" json:"-"`
	Sections       []Section `gorm:"foreignkey:PageId" json:"sections"`
}
