// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package openapi

import (
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func initEvalAPI(db *gorm.DB) EvalAPI {
	evalRepository := ProvideEvalRepository(db)
	evalService := ProvideEvalService(evalRepository)
	evalAPI := ProvideEvalAPI(evalService)
	return evalAPI
}
