/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CourseStats struct for CourseStats
type CourseStats struct {
	// number of questionnaires in the system concerning this course.
	Questionnaires int32 `json:"questionnaires,omitempty"`
}
