/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// TutorReport struct for TutorReport
type TutorReport struct {
	Id string `json:"id,omitempty"`
	TutorId string `json:"tutorId,omitempty"`
	CourseId string `json:"courseId,omitempty"`
	Generated time.Time `json:"generated,omitempty"`
	Sections []ResultSection `json:"sections,omitempty"`
}
