/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// User struct for User
type User struct {
	// login name
	UserName string `json:"userName,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	LastName string `json:"lastName,omitempty"`
	PasswordHash string `json:"passwordHash,omitempty"`
	// login name
	Password string `json:"password,omitempty"`
}
