/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Question struct for Question
type Question struct {
	Id string `json:"id,omitempty"`
	// Unique, humanreadable label.
	Shortcode string `json:"shortcode"`
	// Map of translations for a given string. A string might contain markdown code.
	Title map[string]string `json:"title"`
	// Whether this question is a single choice or multiple choice question
	IsMulti bool `json:"isMulti"`
	// Determines whether it is a free text form. Can not occur with isMulti and hasOtherOption.
	IsComment bool `json:"isComment"`
	// Some questions have an option that allows custom answers
	HasOtherOption bool `json:"hasOtherOption"`
	// Renders this as a slider. Note: Doesnot work with hasOtherOption
	IsSlider bool `json:"isSlider,omitempty"`
	// Question either concerns course, lecturer or tutor.
	Regards string `json:"regards"`
	// Some questions need a not applicable option.
	HasNotApplicableOption bool `json:"hasNotApplicableOption,omitempty"`
	// Defines how results should be displayed.
	Visualizer string `json:"visualizer"`
	// Array of possibly labeled selection options.
	Options []Option `json:"options"`
	// Used to determine position in array
	Position int32 `json:"position,omitempty"`
}
