/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Answer struct for Answer
type Answer struct {
	// Id of courseprof, course o tutor the question is ment for.
	Concerns string `json:"concerns,omitempty"`
	QuestionaireId string `json:"questionaireId"`
	QuestionId string `json:"questionId"`
	NotApplicable bool `json:"notApplicable"`
	Values []string `json:"values"`
}
