/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Term struct for Term
type Term struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name"`
	Begin string `json:"begin"`
	End string `json:"end"`
}
