/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Invitation Onetime invitation to take a certain evaluation of a course.
type Invitation struct {
	Id string `json:"id,omitempty"`
	CourseId string `json:"courseId"`
	ValidBegin time.Time `json:"validBegin,omitempty"`
	ValidEnd time.Time `json:"validEnd,omitempty"`
	Used bool `json:"used,omitempty"`
}
