/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Faculty struct for Faculty
type Faculty struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name"`
}
