/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ThirdPartySendStatus struct for ThirdPartySendStatus
type ThirdPartySendStatus struct {
	Errno        int32  `json:"errno,omitempty"`
	Vid          string `json:"vid,omitempty"`
	Participants int32  `json:"participants,omitempty"`
	Assigned     int32  `json:"assigned,omitempty"`
	Overwritten  int32  `json:"overwritten,omitempty"`
	Notchanged   int32  `json:"notchanged,omitempty"`
}
