/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Form struct for Form
type Form struct {
	Id string `json:"id"`
	Name string `json:"name"`
	TermId string `json:"termId"`
	AbstractForm AbstractForm `json:"abstractForm"`
}
