/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Section struct for Section
type Section struct {
	Id string `json:"id,omitempty"`
	// Map of translations for a given string. A string might contain markdown code.
	Title map[string]string `json:"title"`
	Questions []Question `json:"questions"`
	// Used to determine position in array
	Position int32 `json:"position,omitempty"`
}
