/*
 * Evaluation
 *
 * This API descripes the online evaluation service, as accessed by the user and organizers.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ThirdPartySendSettings struct for ThirdPartySendSettings
type ThirdPartySendSettings struct {
	Begin string `json:"begin,omitempty"`
	End string `json:"end,omitempty"`
	// The URl of the Plattform to be contacted
	PlattformUrl string `json:"plattformUrl,omitempty"`
	// The URl of the the eval system, should end with /
	BaseUrl string `json:"baseUrl,omitempty"`
	// non zero values are meant to force
	Force int32 `json:"force,omitempty"`
}
